resources:
- name: repo
  type: git
  source:
    uri: git@github.com:concourse/examples.git
    branch: master
    private_key: | # how is this done w/o including a priv key? 
    -----BEGIN OPENSSH PRIVATE KEY-----
    ...
    -----END OPENSSH PRIVATE KEY-----

jobs:
- name: hello-world-job
  plan:
  - get: repo
    trigger: true
  - task: create-commit # renamed task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: gitea/gitea # use any image that has the git cli
      inputs:
      - name: repo
      outputs: # Add repo as an output
      - name: repo
      params: # Change these to match your ssh key info
        EMAIL: person@example.com
        GIT_AUTHOR_NAME: Person Doe
      run:
        path: sh
        args:
        - -cx
        # this is just a bash script
        - |
          cd repo
          date +%Y-%m-%d > todays-date
          git add ./todays-date
          git config --global user.email $EMAIL
          git config --global user.name $GIT_AUTHOR_NAME
          git commit -m "Update todays date"
